trigger:
  branches:
    include:
    - master
    - releases/*
    - feature/*
    exclude:
    - releases/old*
    - feature/*-working
  paths:
    include:
    - '*' 
    exclude:
    - '/simpleapp/simpleapi/*' 
    - '/simpleapp/simpleweb/*' 

resources:
- repo: self

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: 'Package'
  displayName: 'Package the helm chart'
  jobs:
   - job: PackageHelmChart
     steps:
       - task: HelmInstaller@1
         displayName: 'Install Helm'
         inputs:
           helmVersionToInstall: 'latest'
       - task: PowerShell@2
         inputs:
           targetType: 'filePath' 
           filePath: helmPackage.ps1
           arguments: -packageDestinationPath $(Build.ArtifactStagingDirectory) -chartSourcePath '$(Build.SourcesDirectory)/simpleapp/charts/simpleapp' -version '1.$(Build.BuildNumber)' -appVersion '$(Build.BuildNumber)'
           workingDirectory: $(Build.SourcesDirectory)

       - task: PublishBuildArtifacts@1
         displayName: 'publish simpleweb helm package for simpleweb as a pipeline artifact'
         inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
- stage: 'DeployToDev'
  displayName: 'Deploy simpleweb and simpleapi to Dev'
  jobs:
    - job: DeployHelmPackage
      steps:
        - task: DownloadBuildArtifacts@0
          displayName: Download the latest helm package
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)'
        - task: HelmInstaller@1
          displayName: Install Helm 
          inputs:
            helmVersionToInstall: 3.1.2
        - task: HelmDeploy@0
          displayName: Deploy simpleweb helm package to the dev aks namespace
          timeoutInMinutes: 5
          inputs:
            connectionType: Kubernetes Service Connection
            kubernetesServiceEndpoint: simpleapp-dev
            namespace: simpleapp-dev
            command: upgrade
            install: true
            chartName: '$(System.ArtifactsDirectory)/drop/simpleapp-1.$(Build.BuildNumber).tgz'
            releaseName: simpleapp
- stage: 'DeployToQA'
  displayName: 'Deploy simpleweb and simpleapi to QA'
  jobs:
    - job: DeployHelmPackage
      steps:
        - task: DownloadBuildArtifacts@0
          displayName: Download the latest helm package
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)'
        - task: HelmInstaller@1
          displayName: Install Helm 
          inputs:
            helmVersionToInstall: 3.1.2
        - task: HelmDeploy@0
          displayName: Deploy simpleweb helm package to the qa aks namespace
          timeoutInMinutes: 5
          inputs:
            connectionType: Kubernetes Service Connection
            kubernetesServiceEndpoint: simpleapp-qa
            namespace: simpleapp-qa
            command: upgrade
            install: true
            chartName: '$(System.ArtifactsDirectory)/drop/simpleapp-1.$(Build.BuildNumber).tgz'
            releaseName: simpleapp

