apiVersion: v1
kind: Pod
metadata:
  name: simpleweb
  labels:
    name: simpleweb
spec:
  containers:
  - name: simpleweb
    image: simpleweb:0.2
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    livenessProbe:
        httpGet:
          path: /ready.html
          port: 80
        initialDelaySeconds: 10
        timeoutSeconds: 2
        periodSeconds: 5
        failureThreshold: 1
